# Generated by Django 4.2.17 on 2024-12-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
