# Generated by Django 4.2.17 on 2024-12-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_profile_cpnumber_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
